---

env:
  global:
    - CI=travis
    - IS_CI=true
    - E2E_CLEANUP=true
    # - PROVIDER="kubernaut"
    - PROVIDER="k3d"
    # PUSH_CHART must be != "false" for pushing the chart
    - PUSH_CHART="true"
    - AWS_BUCKET="datawire-static-files"

install:
  - export PATH=~/bin:$PATH
  - source ~/.gimme/envs/latest.env
  - ./ci/install.sh
  - ./ci/provider.sh setup
  - ./ci/provider.sh create

language: generic

branches:
  only:
  - master
  - /^v.*$/
  - ci-test

script: 
  - ./ci/run_test.sh

after_script:
  - ./ci/provider.sh delete

deploy:
  # package and push the chart to the repository
  - provider: script
    script: bash ./ci/push_chart.sh
    on:
      branch: master
  # generate the manifest used for installing Ambassador with `kubectl apply -f <manifest-url>`
  - provider: script
    script: bash ./ci/push_manifest.sh generate push
    on:
      branch: master
